create table claim
(
    id bigint generated by default as identity,
    description varchar(255),
    is_done     boolean,
    name        varchar(255),
    employee_id bigint,
    claimed_at timestamp,
    primary key (id)
);

create table employee
(
    id bigint generated by default as identity,
    name    varchar(255),
    surname varchar(255),
    primary key (id)
);

alter table claim
    add constraint FKoi7uxmi4i56j4e9lwkgf4757m foreign key (employee_id) references employee;
